# Fix for the large Mall Data file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Your Ganache connection on HP 15s
server.port=8080
# Update this if your Ganache RPC server is different
blockchain.rpc-url=http://127.0.0.1:7545